/**
 * Seed Service
 * ------------
 * Master data from FM-SD-04-05 Rev.01 — 53 fire extinguishers.
 * Grouped by department/zone: SD, BD, FG(BD), WH&LG, CO, EN
 */

import * as repo from '../storage/repository.js';
import { openDB } from '../storage/db.js';

const SAMPLE_EXTINGUISHERS = [
  // ──────────────────────────────────────────
  // แผนก : SD (Safety Department)
  // ──────────────────────────────────────────
  {
    extinguisher_code: 'SD-01',
    serial_no: '',
    location: 'Office',
    department: 'SD',
    extinguisher_type: 'ผงเคมีแห้ง (Dry Chemical)',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },

  // ──────────────────────────────────────────
  // แผนก : BD
  // ──────────────────────────────────────────
  {
    extinguisher_code: 'BD-02',
    serial_no: '',
    location: 'คลัง BD',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },

  // ──────────────────────────────────────────
  // แผนก : BD — โซน FG
  // ──────────────────────────────────────────
  {
    extinguisher_code: 'FG-03',
    serial_no: '',
    location: 'ประตูหน้า FG',
    department: 'BD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-04',
    serial_no: '',
    location: 'หน้าเครื่อง Glue-Auto',
    department: 'BD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-05',
    serial_no: '',
    location: 'หน้าเครื่อง Digital',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-06',
    serial_no: '',
    location: 'เครื่อง DC-3',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-07',
    serial_no: '',
    location: 'เครื่อง DC-5',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-08',
    serial_no: '',
    location: 'เครื่อง P-2',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-09',
    serial_no: '',
    location: 'เครื่อง P-5',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-10',
    serial_no: '',
    location: 'หน้าเครื่อง P-2',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-11',
    serial_no: '',
    location: 'เครื่อง DC-1',
    department: 'BD',
    extinguisher_type: 'CO2',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-12',
    serial_no: '',
    location: 'เครื่อง Slot-Auto',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-13',
    serial_no: '',
    location: 'ประตูข้าง FO',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-14',
    serial_no: '',
    location: 'ประตูข้าง FO',
    department: 'BD',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-15',
    serial_no: '',
    location: 'ชั้น 2-โซนนอน',
    department: 'BD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-16',
    serial_no: '',
    location: 'ชั้น 2-สำนัน',
    department: 'BD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-17',
    serial_no: '',
    location: 'ห้องวัตถุดิบ-wan',
    department: 'BD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'FG-18',
    serial_no: '',
    location: 'ห้องวัตถุดิบ-wan',
    department: 'BD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },

  // ──────────────────────────────────────────
  // แผนก : WH&LG (Warehouse & Logistics)
  // ──────────────────────────────────────────
  {
    extinguisher_code: 'WH-19',
    serial_no: '',
    location: 'คลังหลัง 1',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-20',
    serial_no: '',
    location: 'คลังหลัง 2',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-21',
    serial_no: '',
    location: 'ประตู FO คลังสินค้า 1',
    department: 'WH&LG',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-22',
    serial_no: '',
    location: 'ประตู FO คลังสินค้า',
    department: 'WH&LG',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-23',
    serial_no: '',
    location: 'ประตูคลังสินค้า 1',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-24',
    serial_no: '',
    location: 'ประตูคลังสินค้า 2',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-25',
    serial_no: '',
    location: 'ประตูคลังสินค้า-CO 1',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-26',
    serial_no: '',
    location: 'ประตูคลังสินค้า-CO 2',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-27',
    serial_no: '',
    location: 'ชั้น K1 1125',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-28',
    serial_no: '',
    location: 'ประตูคลังสินค้า',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-29',
    serial_no: '',
    location: 'ประตูคลังสินค้า 1',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-30',
    serial_no: '',
    location: 'คลังสินค้า 1',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-31',
    serial_no: '',
    location: 'คลังสินค้า 2',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-32',
    serial_no: '',
    location: 'Office คลังสินค้า',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-33',
    serial_no: '',
    location: 'ประตูคลังวัตถุดิบ 1',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-34',
    serial_no: '',
    location: 'ประตูคลังวัตถุดิบ 2',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-35',
    serial_no: '',
    location: 'สนุนตะม่อ',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-36',
    serial_no: '',
    location: 'สนุนตะม่อ',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'WH-37',
    serial_no: '',
    location: 'กลางทางเดิน',
    department: 'WH&LG',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },

  // ──────────────────────────────────────────
  // แผนก : CO (Corrugated)
  // ──────────────────────────────────────────
  {
    extinguisher_code: 'CO-38',
    serial_no: '',
    location: 'หน้าเครื่อง',
    department: 'CO',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-39',
    serial_no: '',
    location: 'เครื่อง NC',
    department: 'CO',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-40',
    serial_no: '',
    location: 'ห้องเครื่อง',
    department: 'CO',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-41',
    serial_no: '',
    location: 'ห้องพ่น',
    department: 'CO',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-42',
    serial_no: '',
    location: 'บอยเลอร์ No.1-1',
    department: 'CO',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-43',
    serial_no: '',
    location: 'บอยเลอร์ No.1-2',
    department: 'CO',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-44',
    serial_no: '',
    location: 'บอยเลอร์ No.2-1',
    department: 'CO',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-45',
    serial_no: '',
    location: 'บอยเลอร์ No.2-2',
    department: 'CO',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-46',
    serial_no: '',
    location: 'ห้องพ่นสี 1-1',
    department: 'CO',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-47',
    serial_no: '',
    location: 'ห้องพ่นสี 1-2',
    department: 'CO',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-48',
    serial_no: '',
    location: 'ห้องพ่นสีคู่ 1-1',
    department: 'CO',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'CO-49',
    serial_no: '',
    location: 'ห้องพ่นสีคู่ 1-2',
    department: 'CO',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },

  // ──────────────────────────────────────────
  // แผนก : EN (Engineering)
  // ──────────────────────────────────────────
  {
    extinguisher_code: 'EN-50',
    serial_no: '',
    location: 'ห้องช่าง',
    department: 'EN',
    extinguisher_type: 'BF-2000',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },

  // ──────────────────────────────────────────
  // แผนก : SD (เพิ่มเติม)
  // ──────────────────────────────────────────
  {
    extinguisher_code: 'SD-51',
    serial_no: '',
    location: 'ห้องเก็บ',
    department: 'SD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'SD-52',
    serial_no: '',
    location: 'ห้องค่า',
    department: 'SD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
  {
    extinguisher_code: 'SD-53',
    serial_no: '',
    location: 'ห้อง สปก.',
    department: 'SD',
    extinguisher_type: 'Dry Chemical',
    size: '',
    install_date: '',
    last_service_date: '',
    next_service_due: '',
    status: 'active',
  },
];

export async function seedData() {
  await openDB();

  // Check if already seeded
  const existing = await repo.countExtinguishers();
  if (existing > 0) return false;

  for (const ext of SAMPLE_EXTINGUISHERS) {
    await repo.saveExtinguisher(ext);
  }

  await repo.setSetting('inspector_name', '');
  return true;
}

export async function resetToSeedData() {
  await repo.clearAllData();
  for (const ext of SAMPLE_EXTINGUISHERS) {
    const { id, ...rest } = ext;
    await repo.saveExtinguisher(rest);
  }
  await repo.setSetting('inspector_name', '');
}
